version: "3.7"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    ports:
      - '8080:3000'
    volumes:
      - .:/app
    command: npm run start --production
    container_name: chatlook-be
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql
    ports:
      - '4444:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/db-init.sql:/docker-entrypoint-initdb.d/dump.sql
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
volumes:
  dbdata:
